# Generated by scripts/update-proxy-copilot-homebrew.py in GnouGo/GnouGo.
class GnougoProxyCopilot < Formula
  desc "Standalone local LLM proxy for VS Code Chat and Agent mode"
  homepage "https://github.com/GnouGo/GnouGo/tree/main/src/GnOuGo.ProxyCopilot.Server"
  version "0.20.0"
  license "Apache-2.0"

  on_arm do
    url "https://github.com/GnouGo/GnouGo/releases/download/v#{version}/GnOuGo.ProxyCopilot.Server-osx-arm64-aot.tar.gz"
    sha256 "b2f4459a41bfb662eaa61fe6b1b58b67e4c5847754b9f20c662cb98038b6fe34"
  end

  on_intel do
    url "https://github.com/GnouGo/GnouGo/releases/download/v#{version}/GnOuGo.ProxyCopilot.Server-osx-x64-aot.tar.gz"
    sha256 "1749663bc0707471db0f7d2f1b11659eadb78587bc55580677538496f80cc58e"
  end

  depends_on :macos

  on_macos do
    depends_on macos: :monterey
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"GnOuGo.ProxyCopilot.Server" => "gnougo-proxy-copilot"
  end

  def caveats
    <<~EOS
      Run gnougo-proxy-copilot, then open http://127.0.0.1:5087/ui/.
      Configure providers with ProxyCopilot__Providers__... environment variables.
      Do not store private settings in the Cellar: upgrades replace that directory.
      No background service is started automatically.
    EOS
  end

  test do
    require "net/http"
    require "timeout"

    env = {
      "HOME" => testpath.to_s,
      "TMPDIR" => ENV.fetch("TMPDIR"),
      "PATH" => ENV.fetch("PATH"),
      "DOTNET_ENVIRONMENT" => "Production",
      "ASPNETCORE_ENVIRONMENT" => "Production",
      "OpenTelemetry__Enabled" => "false",
    }
    base = "http://127.0.0.1:#{free_port}"
    pid = spawn(env, (bin/"gnougo-proxy-copilot").to_s, "--urls", base,
                unsetenv_others: true, in: File::NULL,
                out: (testpath/"server.log").to_s, err: [:child, :out])
    begin
      Timeout.timeout(20) do
        loop do
          begin
            response = Net::HTTP.get_response(URI("#{base}/health"))
            assert_equal "200", response.code
            assert_equal "ok", JSON.parse(response.body)["status"]
            break
          rescue Errno::ECONNREFUSED
            sleep 0.2
          end
        end
      end
      assert_match "<html", Net::HTTP.get(URI("#{base}/ui/"))
      assert_empty JSON.parse(Net::HTTP.get(URI("#{base}/v1/models")))["data"]
    ensure
      Process.kill("TERM", pid)
      Process.wait(pid)
    end
  end
end
